//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhRooms.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_customer
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Aadhar { get; set; }
        public string Driving_Licence { get; set; }
        public string Booking_DateTime { get; set; }
        public string Retrun_DateTime { get; set; }
        public Nullable<int> Car_Segments { get; set; }
        public Nullable<int> Hatchback { get; set; }
        public Nullable<int> SUV { get; set; }
        public Nullable<int> Sedan { get; set; }
    }
}
